# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-10-19 06:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_goodsvisitcount'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='goodsvisitcount',
            unique_together=set([('date', 'category')]),
        ),
    ]
